### ISSUE TITLE
[1.16.1] Unable to load MFM, null error

### ISSUE THREAD

**Issue by mrfloris** [Zrips/MobFarmManager#1]
Sorry, still gonna report these.. 

```
[04:14:07] [Server thread/INFO]: [MobFarmManager] Enabling MobFarmManager v1.5.5.3
[04:14:08] [Server thread/WARN]: Initializing Legacy Material Support. Unless you have legacy plugins and/or data this is a bug!
[04:14:10] [Server thread/INFO]: Your server version is not compatible with this plugins version! Plugin will be disabled: v1_16
[04:14:10] [Server thread/ERROR]: Error occurred while enabling MobFarmManager v1.5.5.3 (Is it up to date?)
java.lang.NullPointerException: null
	at com.MobFarmManager.Zrips.MFM.onDisable(MFM.java:66) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[spigot-1.16.1.jar:git-Spigot-758abbe-2b00831]
	at com.MobFarmManager.Zrips.MFM.onEnable(MFM.java:90) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[spigot-1.16.1.jar:git-Spigot-758abbe-2b00831]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:351) ~[spigot-1.16.1.jar:git-Spigot-758abbe-2b00831]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[spigot-1.16.1.jar:git-Spigot-758abbe-2b00831]
	at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugin(CraftServer.java:488) ~[spigot-1.16.1.jar:git-Spigot-758abbe-2b00831]
	at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugins(CraftServer.java:402) ~[spigot-1.16.1.jar:git-Spigot-758abbe-2b00831]
	at net.minecraft.server.v1_16_R1.MinecraftServer.loadWorld(MinecraftServer.java:436) ~[spigot-1.16.1.jar:git-Spigot-758abbe-2b00831]
	at net.minecraft.server.v1_16_R1.DedicatedServer.init(DedicatedServer.java:219) ~[spigot-1.16.1.jar:git-Spigot-758abbe-2b00831]
	at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:808) ~[spigot-1.16.1.jar:git-Spigot-758abbe-2b00831]
	at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[spigot-1.16.1.jar:git-Spigot-758abbe-2b00831]
	at java.lang.Thread.run(Thread.java:834) [?:?]
[04:14:10] [Server thread/INFO]: Server permissions file permissions.yml is empty, ignoring it
[04:14:10] [Server thread/INFO]: Done (21.532s)! For help, type "help"
```
```
>ver
[04:15:04] [Server thread/INFO]: This server is running CraftBukkit version git-Spigot-758abbe-2b00831 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)
[04:15:04] [Server thread/INFO]: Checking version, please wait...
[04:15:04] [Thread-7/INFO]: You are running the latest version
>
```

**Comment by CloudeLecaw** [comment]
Thank you mrfloris for using this github <3

**Comment by mrfloris** [comment]
I am using this on 1.16.5 without issues on paper now, so I can close this.
