### ISSUE TITLE
Folia Error

### ISSUE THREAD

**Issue by Stabrinai** [Zrips/MobFarmManager#56]
MobFarmManager v2.1.0.3
CMILib v1.4.2.0

![image](https://github.com/Zrips/MobFarmManager/assets/61693182/163c5aa2-500b-4dd3-9539-56d61deafdaa)

```java
[13:57:56] [Folia Async Scheduler Thread #54/ERROR]: Thread Folia Async Scheduler Thread #54 failed main thread check: Accessing entity state off owning region's thread
java.lang.Throwable: null
	at io.papermc.paper.util.TickThread.ensureTickThread(TickThread.java:78) ~[folia-1.20.1.jar:git-Folia-"80a9339"]
	at org.bukkit.craftbukkit.v1_20_R1.entity.CraftArmorStand.getHandle(CraftArmorStand.java:32) ~[folia-1.20.1.jar:git-Folia-"80a9339"]
	at org.bukkit.craftbukkit.v1_20_R1.entity.CraftArmorStand.getHandle(CraftArmorStand.java:12) ~[folia-1.20.1.jar:git-Folia-"80a9339"]
	at org.bukkit.craftbukkit.v1_20_R1.entity.CraftLivingEntity.isInvisible(CraftLivingEntity.java:928) ~[folia-1.20.1.jar:git-Folia-"80a9339"]
	at com.MobFarmManager.Zrips.Util.ChunkManager.CheckChunk(ChunkManager.java:456) ~[MobFarmManager.jar:?]
	at com.MobFarmManager.Zrips.Util.ChunkManager.runCleaner(ChunkManager.java:119) ~[MobFarmManager.jar:?]
	at com.MobFarmManager.Zrips.Util.ChunkManager.runAutoCleaner(ChunkManager.java:86) ~[MobFarmManager.jar:?]
	at com.MobFarmManager.Zrips.Util.ChunkManager.initiateCleaner(ChunkManager.java:264) ~[MobFarmManager.jar:?]
	at com.MobFarmManager.Zrips.Util.ChunkManager.lambda$0(ChunkManager.java:80) ~[MobFarmManager.jar:?]
	at net.Zrips.CMILib.Version.Schedulers.CMIFoliaImpl.lambda$runTimerAsync$5(CMIFoliaImpl.java:71) ~[CMILib.jar:?]
	at io.papermc.paper.threadedregions.scheduler.FoliaAsyncScheduler$AsyncScheduledTask.run(FoliaAsyncScheduler.java:217) ~[folia-1.20.1.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

**Comment by Zrips** [comment]
Should be fixed with next version
