### ISSUE TITLE
Console Error, unsure of cause, possibly wolf

### ISSUE THREAD

**Issue by Strahilchu** [Zrips/MobFarmManager#66]
[23:23:33 WARN]: java.lang.IllegalStateException: EntityToggleSitEvent may only be triggered synchronously.
[23:23:33 WARN]:        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:42)
[23:23:33 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126)
[23:23:33 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617)
[23:23:33 WARN]:        at org.bukkit.event.Event.callEvent(Event.java:45)
[23:23:33 WARN]:        at net.minecraft.world.entity.EntityTameableAnimal.setInSittingPose(EntityTameableAnimal.java:132)
[23:23:33 WARN]:        at net.minecraft.world.entity.EntityTameableAnimal.y(EntityTameableAnimal.java:129)
[23:23:33 WARN]:        at org.bukkit.craftbukkit.v1_20_R3.entity.CraftTameableAnimal.setSitting(CraftTameableAnimal.java:80)
[23:23:33 WARN]:        at MobFarmManager2.1.0.6.jar//com.MobFarmManager.Zrips.Util.ChunkManager.CheckChunk(ChunkManager.java:486)
[23:23:33 WARN]:        at MobFarmManager2.1.0.6.jar//com.MobFarmManager.Zrips.Util.ChunkManager.runCleaner(ChunkManager.java:167)
[23:23:33 WARN]:        at MobFarmManager2.1.0.6.jar//com.MobFarmManager.Zrips.Util.ChunkManager.runAutoCleaner(ChunkManager.java:82)
[23:23:33 WARN]:        at MobFarmManager2.1.0.6.jar//com.MobFarmManager.Zrips.Util.ChunkManager.initiateCleaner(ChunkManager.java:274)
[23:23:33 WARN]:        at MobFarmManager2.1.0.6.jar//com.MobFarmManager.Zrips.Util.ChunkManager.lambda$0(ChunkManager.java:77)
[23:23:33 WARN]:        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101)
[23:23:33 WARN]:        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[23:23:33 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[23:23:33 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[23:23:33 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[23:23:33 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1589)
[23:23:33 WARN]: java.lang.IllegalStateException: EntityToggleSitEvent may only be triggered synchronously.
[23:23:33 WARN]:        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:42)
[23:23:33 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126)
[23:23:33 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617)
[23:23:33 WARN]:        at org.bukkit.event.Event.callEvent(Event.java:45)
[23:23:33 WARN]:        at net.minecraft.world.entity.EntityTameableAnimal.setInSittingPose(EntityTameableAnimal.java:132)
[23:23:33 WARN]:        at net.minecraft.world.entity.EntityTameableAnimal.y(EntityTameableAnimal.java:129)
[23:23:33 WARN]:        at org.bukkit.craftbukkit.v1_20_R3.entity.CraftTameableAnimal.setSitting(CraftTameableAnimal.java:80)
[23:23:33 WARN]:        at MobFarmManager2.1.0.6.jar//com.MobFarmManager.Zrips.Util.ChunkManager.CheckChunk(ChunkManager.java:486)
[23:23:33 WARN]:        at MobFarmManager2.1.0.6.jar//com.MobFarmManager.Zrips.Util.ChunkManager.runCleaner(ChunkManager.java:167)
[23:23:33 WARN]:        at MobFarmManager2.1.0.6.jar//com.MobFarmManager.Zrips.Util.ChunkManager.runAutoCleaner(ChunkManager.java:82)
[23:23:33 WARN]:        at MobFarmManager2.1.0.6.jar//com.MobFarmManager.Zrips.Util.ChunkManager.initiateCleaner(ChunkManager.java:274)
[23:23:33 WARN]:        at MobFarmManager2.1.0.6.jar//com.MobFarmManager.Zrips.Util.ChunkManager.lambda$0(ChunkManager.java:77)
[23:23:33 WARN]:        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101)
[23:23:33 WARN]:        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[23:23:33 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[23:23:33 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[23:23:33 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[23:23:33 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1589)

**Comment by Zrips** [comment]
Should be resolved with latest builds
