### ISSUE TITLE
Console error, over and over again : java.lang.NoSuchFieldException:i

### ISSUE THREAD

**Issue by aesopcmc** [Zrips/MobFarmManager#67]
CMILib1.4.2.1
MobFarmManager-2.1.0.6
paper: 1.19.4

[23:26:29 WARN]: java.lang.NoSuchFieldException: i
[23:26:29 WARN]:        at java.base/java.lang.Class.getDeclaredField(Class.java:2610)
[23:26:29 WARN]:        at MobFarmManager2.1.0.6.jar//com.MobFarmManager.Zrips.Reflections.lambda$0(Reflections.java:122)
[23:26:29 WARN]:        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftTask.run(CraftTask.java:101)
[23:26:29 WARN]:        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
[23:26:29 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1483)
[23:26:29 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:447)
[23:26:29 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1174)
[23:26:29 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320)
[23:26:32 WARN]: java.lang.NoSuchFieldException: i
[23:26:32 WARN]:        at java.base/java.lang.Class.getDeclaredField(Class.java:2610)
[23:26:32 WARN]:        at MobFarmManager2.1.0.6.jar//com.MobFarmManager.Zrips.Reflections.lambda$0(Reflections.java:122)
[23:26:32 WARN]:        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftTask.run(CraftTask.java:101)
[23:26:32 WARN]:        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
[23:26:32 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1483)
[23:26:32 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:447)
[23:26:32 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1174)
[23:26:32 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320)

**Comment by Zrips** [comment]
Should be resolved with next update
