### ISSUE TITLE
Error on 1.21

### ISSUE THREAD

**Issue by PabloKateee** [Zrips/MobFarmManager#73]
[19:20:47] [ForkJoinPool.commonPool-worker-275/WARN]: java.util.concurrent.RejectedExecutionException: Thread limit exceeded replacing blocked worker
[19:20:47] [ForkJoinPool.commonPool-worker-275/WARN]: 	at java.base/java.util.concurrent.ForkJoinPool.tryCompensate(ForkJoinPool.java:2243)
[19:20:47] [ForkJoinPool.commonPool-worker-275/WARN]: 	at java.base/java.util.concurrent.ForkJoinPool.compensatedBlock(ForkJoinPool.java:3975)
[19:20:47] [ForkJoinPool.commonPool-worker-275/WARN]: 	at java.base/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3959)
[19:20:47] [ForkJoinPool.commonPool-worker-275/WARN]: 	at java.base/java.util.concurrent.CompletableFuture.waitingGet(CompletableFuture.java:1898)
[19:20:47] [ForkJoinPool.commonPool-worker-275/WARN]: 	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2072)
[19:20:47] [ForkJoinPool.commonPool-worker-275/WARN]: 	at MobFarmManager3.0.0.3-1720256355690.jar//com.MobFarmManager.Zrips.Util.CleanerManager.lambda$8(CleanerManager.java:296)
[19:20:47] [ForkJoinPool.commonPool-worker-275/WARN]: 	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
[19:20:47] [ForkJoinPool.commonPool-worker-275/WARN]: 	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483)
[19:20:47] [ForkJoinPool.commonPool-worker-275/WARN]: 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:507)
[19:20:47] [ForkJoinPool.commonPool-worker-275/WARN]: 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1491)
[19:20:47] [ForkJoinPool.commonPool-worker-275/WARN]: 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:2073)
[19:20:47] [ForkJoinPool.commonPool-worker-275/WARN]: 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:2035)
[19:20:47] [ForkJoinPool.commonPool-worker-275/WARN]: 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:187)
[19:20:47] [ForkJoinPool.commonPool-worker-275/WARN]: java.lang.InterruptedException
[19:20:47] [ForkJoinPool.commonPool-worker-275/WARN]: 	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:386)
[19:20:47] [ForkJoinPool.commonPool-worker-275/WARN]: 	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073)
[19:20:47] [ForkJoinPool.commonPool-worker-275/WARN]: 	at MobFarmManager3.0.0.3-1720256355690.jar//com.MobFarmManager.Zrips.Util.CleanerManager.lambda$8(CleanerManager.java:296)
[19:20:47] [ForkJoinPool.commonPool-worker-275/WARN]: 	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
[19:20:47] [ForkJoinPool.commonPool-worker-275/WARN]: 	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483)
[19:20:47] [ForkJoinPool.commonPool-worker-275/WARN]: 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:507)
[19:20:47] [ForkJoinPool.commonPool-worker-275/WARN]: 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1491)
[19:20:47] [ForkJoinPool.commonPool-worker-275/WARN]: 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:2073)
[19:20:47] [ForkJoinPool.commonPool-worker-275/WARN]: 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:2035)
[19:20:47] [ForkJoinPool.commonPool-worker-275/WARN]: 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:187)
[19:20:47] [ForkJoinPool.commonPool-worker-275/WARN]: java.lang.InterruptedException
[19:20:47] [ForkJoinPool.commonPool-worker-275/WARN]: 	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:386)
[19:20:47] [ForkJoinPool.commonPool-worker-275/WARN]: 	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073)
[19:20:47] [ForkJoinPool.commonPool-worker-275/WARN]: 	at MobFarmManager3.0.0.3-1720256355690.jar//com.MobFarmManager.Zrips.Util.CleanerManager.lambda$8(CleanerManager.java:296)
[19:20:47] [ForkJoinPool.commonPool-worker-275/WARN]: 	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
[19:20:47] [ForkJoinPool.commonPool-worker-275/WARN]: 	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483)
[19:20:47] [ForkJoinPool.commonPool-worker-275/WARN]: 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:507)
[19:20:47] [ForkJoinPool.commonPool-worker-275/WARN]: 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1491)
[19:20:47] [ForkJoinPool.commonPool-worker-275/WARN]: 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:2073)
[19:20:47] [ForkJoinPool.commonPool-worker-275/WARN]: 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:2035)
[19:20:47] [ForkJoinPool.commonPool-worker-275/WARN]: 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:187)
[19:20:47] [ForkJoinPool.commonPool-worker-275/WARN]: java.lang.InterruptedException
[19:20:47] [ForkJoinPool.commonPool-worker-275/WARN]: 	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:386)
[19:20:47] [ForkJoinPool.commonPool-worker-275/WARN]: 	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073)
[19:20:47] [ForkJoinPool.commonPool-worker-275/WARN]: 	at MobFarmManager3.0.0.3-1720256355690.jar//com.MobFarmManager.Zrips.Util.CleanerManager.lambda$8(CleanerManager.java:296)
[19:20:47] [ForkJoinPool.commonPool-worker-275/WARN]: 	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
[19:20:47] [ForkJoinPool.commonPool-worker-275/WARN]: 	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483)
[19:20:47] [ForkJoinPool.commonPool-worker-275/WARN]: 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:507)
[19:20:47] [ForkJoinPool.commonPool-worker-275/WARN]: 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1491)
[19:20:47] [ForkJoinPool.commonPool-worker-275/WARN]: 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:2073)
[19:20:47] [ForkJoinPool.commonPool-worker-275/WARN]: 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:2035)
[19:20:47] [ForkJoinPool.commonPool-worker-275/WARN]: 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:187)
[19:20:47] [ForkJoinPool.commonPool-worker-275/WARN]: java.lang.InterruptedException
[19:20:47] [ForkJoinPool.commonPool-worker-275/WARN]: 	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:386)
[19:20:47] [ForkJoinPool.commonPool-worker-275/WARN]: 	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073)
[19:20:47] [ForkJoinPool.commonPool-worker-275/WARN]: 	at MobFarmManager3.0.0.3-1720256355690.jar//com.MobFarmManager.Zrips.Util.CleanerManager.lambda$8(CleanerManager.java:296)
[19:20:47] [ForkJoinPool.commonPool-worker-275/WARN]: 	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
[19:20:47] [ForkJoinPool.commonPool-worker-275/WARN]: 	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483)
[19:20:47] [ForkJoinPool.commonPool-worker-275/WARN]: 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:507)
[19:20:47] [ForkJoinPool.commonPool-worker-275/WARN]: 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1491)
[19:20:47] [ForkJoinPool.commonPool-worker-275/WARN]: 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:2073)
[19:20:47] [ForkJoinPool.commonPool-worker-275/WARN]: 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:2035)
[19:20:47] [ForkJoinPool.commonPool-worker-275/WARN]: 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:187)
[19:20:47] [ForkJoinPool.commonPool-worker-275/WARN]: java.lang.InterruptedException
[19:20:47] [ForkJoinPool.commonPool-worker-275/WARN]: 	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:386)
[19:20:47] [ForkJoinPool.commonPool-worker-275/WARN]: 	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073)
[19:20:47] [ForkJoinPool.commonPool-worker-275/WARN]: 	at MobFarmManager3.0.0.3-1720256355690.jar//com.MobFarmManager.Zrips.Util.CleanerManager.lambda$8(CleanerManager.java:296)
[19:20:47] [ForkJoinPool.commonPool-worker-275/WARN]: 	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
[19:20:47] [ForkJoinPool.commonPool-worker-275/WARN]: 	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483)
[19:20:47] [ForkJoinPool.commonPool-worker-275/WARN]: 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:507)
[19:20:47] [ForkJoinPool.commonPool-worker-275/WARN]: 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1491)
[19:20:47] [ForkJoinPool.commonPool-worker-275/WARN]: 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:2073)
[19:20:47] [ForkJoinPool.commonPool-worker-275/WARN]: 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:2035)
[19:20:47] [ForkJoinPool.commonPool-worker-275/WARN]: 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:187)
[19:20:47] [ForkJoinPool.commonPool-worker-275/WARN]: java.lang.InterruptedException
[19:20:47] [ForkJoinPool.commonPool-worker-275/WARN]: 	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:386)
[19:20:47] [ForkJoinPool.commonPool-worker-275/WARN]: 	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073)
[19:20:47] [ForkJoinPool.commonPool-worker-275/WARN]: 	at MobFarmManager3.0.0.3-1720256355690.jar//com.MobFarmManager.Zrips.Util.CleanerManager.lambda$8(CleanerManager.java:296)
[19:20:47] [ForkJoinPool.commonPool-worker-275/WARN]: 	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
[19:20:47] [ForkJoinPool.commonPool-worker-275/WARN]: 	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483)
[19:20:47] [ForkJoinPool.commonPool-worker-275/WARN]: 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:507)
[19:20:47] [ForkJoinPool.commonPool-worker-275/WARN]: 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1491)
[19:20:47] [ForkJoinPool.commonPool-worker-275/WARN]: 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:2073)
[19:20:47] [ForkJoinPool.commonPool-worker-275/WARN]: 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:2035)
[19:20:47] [ForkJoinPool.commonPool-worker-275/WARN]: 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:187)
[19:20:47] [ForkJoinPool.commonPool-worker-275/WARN]: java.lang.InterruptedException
[19:20:47] [ForkJoinPool.commonPool-worker-275/WARN]: 	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:386)
[19:20:47] [ForkJoinPool.commonPool-worker-275/WARN]: 	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073)
[19:20:47] [ForkJoinPool.commonPool-worker-275/WARN]: 	at MobFarmManager3.0.0.3-1720256355690.jar//com.MobFarmManager.Zrips.Util.CleanerManager.lambda$8(CleanerManager.java:296)
[19:20:47] [ForkJoinPool.commonPool-worker-275/WARN]: 	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
[19:20:47] [ForkJoinPool.commonPool-worker-275/WARN]: 	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483)
[19:20:47] [ForkJoinPool.commonPool-worker-275/WARN]: 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:507)
[19:20:47] [ForkJoinPool.commonPool-worker-275/WARN]: 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1491)
[19:20:47] [ForkJoinPool.commonPool-worker-275/WARN]: 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:2073)
[19:20:47] [ForkJoinPool.commonPool-worker-275/WARN]: 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:2035)
[19:20:47] [ForkJoinPool.commonPool-worker-275/WARN]: 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:187)
[19:20:47] [ForkJoinPool.commonPool-worker-275/WARN]: java.lang.InterruptedException
[19:20:47] [ForkJoinPool.commonPool-worker-275/WARN]: 	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:386)
[19:20:47] [ForkJoinPool.commonPool-worker-275/WARN]: 	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073)
[19:20:47] [ForkJoinPool.commonPool-worker-275/WARN]: 	at MobFarmManager3.0.0.3-1720256355690.jar//com.MobFarmManager.Zrips.Util.CleanerManager.lambda$8(CleanerManager.java:296)
[19:20:47] [ForkJoinPool.commonPool-worker-275/WARN]: 	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
[19:20:47] [ForkJoinPool.commonPool-worker-275/WARN]: 	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483)
[19:20:47] [ForkJoinPool.commonPool-worker-275/WARN]: 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:507)
[19:20:47] [ForkJoinPool.commonPool-worker-275/WARN]: 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1491)
[19:20:47] [ForkJoinPool.commonPool-worker-275/WARN]: 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:2073)
[19:20:47] [ForkJoinPool.commonPool-worker-275/WARN]: 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:2035)
[19:20:47] [ForkJoinPool.commonPool-worker-275/WARN]: 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:187)
[19:20:47] [ForkJoinPool.commonPool-worker-275/WARN]: java.lang.InterruptedException
[19:20:47] [ForkJoinPool.commonPool-worker-275/WARN]: 	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:386)
[19:20:47] [ForkJoinPool.commonPool-worker-275/WARN]: 	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073)
[19:20:47] [ForkJoinPool.commonPool-worker-275/WARN]: 	at MobFarmManager3.0.0.3-1720256355690.jar//com.MobFarmManager.Zrips.Util.CleanerManager.lambda$8(CleanerManager.java:296)
[19:20:47] [ForkJoinPool.commonPool-worker-275/WARN]: 	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
[19:20:47] [ForkJoinPool.commonPool-worker-275/WARN]: 	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483)
[19:20:47] [ForkJoinPool.commonPool-worker-275/WARN]: 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:507)
[19:20:47] [ForkJoinPool.commonPool-worker-275/WARN]: 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1491)
[19:20:47] [ForkJoinPool.commonPool-worker-275/WARN]: 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:2073)
[19:20:47] [ForkJoinPool.commonPool-worker-275/WARN]: 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:2035)
[19:20:47] [ForkJoinPool.commonPool-worker-275/WARN]: 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:187)
[19:20:47] [ForkJoinPool.commonPool-worker-275/WARN]: java.lang.InterruptedException
[19:20:47] [ForkJoinPool.commonPool-worker-275/WARN]: 	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:386)
[19:20:47] [ForkJoinPool.commonPool-worker-275/WARN]: 	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073)
[19:20:47] [ForkJoinPool.commonPool-worker-275/WARN]: 	at MobFarmManager3.0.0.3-1720256355690.jar//com.MobFarmManager.Zrips.Util.CleanerManager.lambda$8(CleanerManager.java:296)
[19:20:47] [ForkJoinPool.commonPool-worker-275/WARN]: 	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
[19:20:47] [ForkJoinPool.commonPool-worker-275/WARN]: 	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483)
[19:20:47] [ForkJoinPool.commonPool-worker-275/WARN]: 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:507)
[19:20:47] [ForkJoinPool.commonPool-worker-275/WARN]: 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1491)
[19:20:47] [ForkJoinPool.commonPool-worker-275/WARN]: 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:2073)
[19:20:47] [ForkJoinPool.commonPool-worker-275/WARN]: 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:2035)
[19:20:47] [ForkJoinPool.commonPool-worker-275/WARN]: 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:187)
[19:20:47] [ForkJoinPool.commonPool-worker-275/WARN]: java.lang.InterruptedException
[19:20:47] [ForkJoinPool.commonPool-worker-275/WARN]: 	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:386)
[19:20:47] [ForkJoinPool.commonPool-worker-275/WARN]: 	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073)
[19:20:47] [ForkJoinPool.commonPool-worker-275/WARN]: 	at MobFarmManager3.0.0.3-1720256355690.jar//com.MobFarmManager.Zrips.Util.CleanerManager.lambda$8(CleanerManager.java:296)
[19:20:47] [ForkJoinPool.commonPool-worker-275/WARN]: 	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
[19:20:47] [ForkJoinPool.commonPool-worker-275/WARN]: 	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483)
[19:20:47] [ForkJoinPool.commonPool-worker-275/WARN]: 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:507)
[19:20:47] [ForkJoinPool.commonPool-worker-275/WARN]: 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1491)
[19:20:47] [ForkJoinPool.commonPool-worker-275/WARN]: 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:2073)
[19:20:47] [ForkJoinPool.commonPool-worker-275/WARN]: 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:2035)
[19:20:47] [ForkJoinPool.commonPool-worker-275/WARN]: 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:187)
[19:20:47] [ForkJoinPool.commonPool-worker-275/WARN]: java.lang.InterruptedException
[19:20:47] [ForkJoinPool.commonPool-worker-275/WARN]: 	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:386)
[19:20:47] [ForkJoinPool.commonPool-worker-275/WARN]: 	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073)
[19:20:47] [ForkJoinPool.commonPool-worker-275/WARN]: 	at MobFarmManager3.0.0.3-1720256355690.jar//com.MobFarmManager.Zrips.Util.CleanerManager.lambda$8(CleanerManager.java:296)
[19:20:47] [ForkJoinPool.commonPool-worker-275/WARN]: 	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
[19:20:47] [ForkJoinPool.commonPool-worker-275/WARN]: 	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483)
[19:20:47] [ForkJoinPool.commonPool-worker-275/WARN]: 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:507)
[19:20:47] [ForkJoinPool.commonPool-worker-275/WARN]: 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1491)
[19:20:47] [ForkJoinPool.commonPool-worker-275/WARN]: 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:2073)
[19:20:47] [ForkJoinPool.commonPool-worker-275/WARN]: 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:2035)
[19:20:47] [ForkJoinPool.commonPool-worker-275/WARN]: 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:187)
[19:20:47] [ForkJoinPool.commonPool-worker-275/WARN]: java.lang.InterruptedException
[19:20:47] [ForkJoinPool.commonPool-worker-275/WARN]: 	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:386)
[19:20:47] [ForkJoinPool.commonPool-worker-275/WARN]: 	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073)
[19:20:47] [ForkJoinPool.commonPool-worker-275/WARN]: 	at MobFarmManager3.0.0.3-1720256355690.jar//com.MobFarmManager.Zrips.Util.CleanerManager.lambda$8(CleanerManager.java:296)
[19:20:47] [ForkJoinPool.commonPool-worker-275/WARN]: 	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
[19:20:47] [ForkJoinPool.commonPool-worker-275/WARN]: 	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483)
[19:20:47] [ForkJoinPool.commonPool-worker-275/WARN]: 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:507)
[19:20:47] [ForkJoinPool.commonPool-worker-275/WARN]: 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1491)
[19:20:47] [ForkJoinPool.commonPool-worker-275/WARN]: 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:2073)
[19:20:47] [ForkJoinPool.commonPool-worker-275/WARN]: 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:2035)
[19:20:47] [ForkJoinPool.commonPool-worker-275/WARN]: 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:187)
[19:20:47] [ForkJoinPool.commonPool-worker-275/WARN]: java.lang.InterruptedException
[19:20:47] [ForkJoinPool.commonPool-worker-275/WARN]: 	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:386)
[19:20:47] [ForkJoinPool.commonPool-worker-275/WARN]: 	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073)
[19:20:47] [ForkJoinPool.commonPool-worker-275/WARN]: 	at MobFarmManager3.0.0.3-1720256355690.jar//com.MobFarmManager.Zrips.Util.CleanerManager.lambda$8(CleanerManager.java:296)
[19:20:47] [ForkJoinPool.commonPool-worker-275/WARN]: 	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
[19:20:47] [ForkJoinPool.commonPool-worker-275/WARN]: 	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483)
[19:20:47] [ForkJoinPool.commonPool-worker-275/WARN]: 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:507)
[19:20:47] [ForkJoinPool.commonPool-worker-275/WARN]: 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1491)
[19:20:47] [ForkJoinPool.commonPool-worker-275/WARN]: 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:2073)
[19:20:47] [ForkJoinPool.commonPool-worker-275/WARN]: 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:2035)
[19:20:47] [ForkJoinPool.commonPool-worker-275/WARN]: 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:187)

**Comment by Zrips** [comment]
Try out new version 3.0.0.4

**Comment by PabloKateee** [comment]
Best Developer
