### ISSUE TITLE
[ISSUE]

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/MobFarmManager#77]
This one come to my console and i see no reason for it
Also it just pops out a few times.. so may you see a reason for..

```
[19:38:27] [Craft Scheduler Thread - 1360 - CMILib/WARN]: java.util.concurrent.ExecutionException: java.util.concurrent.TimeoutException
[19:38:27] [Craft Scheduler Thread - 1360 - CMILib/WARN]: 	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396)
[19:38:27] [Craft Scheduler Thread - 1360 - CMILib/WARN]: 	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073)
[19:38:27] [Craft Scheduler Thread - 1360 - CMILib/WARN]: 	at MobFarmManager_3.0.1.6.jar//com.MobFarmManager.Zrips.Util.AutoCleanerManager.processAutoClean(AutoCleanerManager.java:106)
[19:38:27] [Craft Scheduler Thread - 1360 - CMILib/WARN]: 	at MobFarmManager_3.0.1.6.jar//com.MobFarmManager.Zrips.Util.AutoCleanerManager.lambda$0(AutoCleanerManager.java:46)
[19:38:27] [Craft Scheduler Thread - 1360 - CMILib/WARN]: 	at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101)
[19:38:27] [Craft Scheduler Thread - 1360 - CMILib/WARN]: 	at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[19:38:27] [Craft Scheduler Thread - 1360 - CMILib/WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[19:38:27] [Craft Scheduler Thread - 1360 - CMILib/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[19:38:27] [Craft Scheduler Thread - 1360 - CMILib/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[19:38:27] [Craft Scheduler Thread - 1360 - CMILib/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:1583)
[19:38:27] [Craft Scheduler Thread - 1360 - CMILib/WARN]: Caused by: java.util.concurrent.TimeoutException
[19:38:27] [Craft Scheduler Thread - 1360 - CMILib/WARN]: 	at java.base/java.util.concurrent.CompletableFuture$Timeout.run(CompletableFuture.java:2920)
[19:38:27] [Craft Scheduler Thread - 1360 - CMILib/WARN]: 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
[19:38:27] [Craft Scheduler Thread - 1360 - CMILib/WARN]: 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
[19:38:27] [Craft Scheduler Thread - 1360 - CMILib/WARN]: 	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
[19:38:27] [Craft Scheduler Thread - 1360 - CMILib/WARN]: 	... 3 more
```

**Comment by HorusApl** [comment]
Also having this exact error and seems to have a decent TPS hit as well.

**Comment by Zrips** [comment]
Should be resolved with next update.
@HorusApl that tps drop is backwards, it dropped not because plugin error out, but plugin errored out because TPS dropped
