### ISSUE TITLE
[1.21 ISSUE] Mob limits not working. Mobs not deleting when over limit.

### ISSUE THREAD

**Issue by Valeoria** [Zrips/MobFarmManager#79]
I've just updated my test server to 1.21 and during testing I found MFM is not clearing mobs when they hit the configured limits.

I have made no changes to the config, the current config works fine on 1.20.4. There are no startup errors in console, the plugin appears to be loading without issue. I do sometimes get an error during uptime that does mention MFM, but I don't know enough to know if this error is related to the issue or not. I will paste it below.

**Server versions:**

- Purpur 1.21-2278-b3623fa
- MobFarmManager 3.0.1.6
- CMI 9.7.4.9
- CMILIB 1.5.1.0

`01/08/2024 [17:25:51 WARN]: java.util.concurrent.ExecutionException: java.lang.NullPointerException: Cannot invoke "org.bukkit.Chunk.getEntities()" because "<
local5>" is null
[17:25:51 WARN]:    at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396)
[17:25:51 WARN]:    at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073)
[17:25:51 WARN]:    at MobFarmManager3.0.1.6.jar//com.MobFarmManager.Zrips.Util.AutoCleanerManager.processAutoClean(AutoCleanerManager.java:106)
[17:25:51 WARN]:    at MobFarmManager3.0.1.6.jar//com.MobFarmManager.Zrips.Util.AutoCleanerManager.lambda$0(AutoCleanerManager.java:46)
[17:25:51 WARN]:    at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:86)
01/08/2024 [17:25:51 WARN]:     at org.bukkit.craftbukkit.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[17:25:51 WARN]:    at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[17:25:51 WARN]:    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[17:25:51 WARN]:    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[17:25:51 WARN]:    at java.base/java.lang.Thread.run(Thread.java:1583)
01/08/2024 [17:25:51 WARN]: Caused by: java.lang.NullPointerException: Cannot invoke "org.bukkit.Chunk.getEntities()" because "<local5>" is null
01/08/2024 [17:25:51 WARN]:     at MobFarmManager3.0.1.6.jar//com.MobFarmManager.Zrips.Util.CleanerManager.lambda$16(CleanerManager.java:701)
01/08/2024 [17:25:51 WARN]:     at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
[17:25:51 WARN]:    at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
[17:25:51 WARN]:
01/08/2024  at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2179)
01/08/2024 
01/08/2024 >....
01/08/2024 [17:25:51 WARN]:
01/08/2024 at org.bukkit.craftbukkit.CraftWorld.lambda$getChunkAtAsync$14(CraftWorld.java:2474)
01/08/2024 
[17:25:51 WARN]:    at net.minecraft.server.TickTask.run(TickTask.java:18)
[17:25:51 WARN]:    at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151)
[17:25:51 WARN]:    at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24)
[17:25:51 WARN]:    at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1573)
[17:25:51 WARN]:    at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201)
01/08/2024 [17:25:51 WARN]:     at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125)
01/08/2024 [17:25:51 WARN]:     at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1550)
[17:25:51 WARN]:    at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1543)
[17:25:51 WARN]:    at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135)
01/08/2024 [17:25:51 WARN]:     at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1502)
[17:25:51 WARN]:    at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1509)
[17:25:51 WARN]:    at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1354)
[17:25:51 WARN]:    at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:333)
[17:25:51 WARN]:    ... 1 more `

**Comment by Zrips** [comment]
Will be fixed with next version
