### ISSUE TITLE
Error in Console

### ISSUE THREAD

**Issue by w1th0utme** [Zrips/MobFarmManager#80]
Installed the latest version of the plugin and saw the following errors in the console, what could be the problem? Server version 1.20.4

```
[02:15:11 WARN]: java.lang.InterruptedException
[02:15:11 WARN]:        at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:386)
[02:15:11 WARN]:        at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073)
[02:15:11 WARN]:        at MobFarmManager3.0.1.7.jar//com.MobFarmManager.Zrips.Util.CleanerManager.lambda$8(CleanerManager.java:292)
[02:15:11 WARN]:        at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
[02:15:11 WARN]:        at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483)
[02:15:11 WARN]:        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
[02:15:11 WARN]:        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
[02:15:11 WARN]:        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
[02:15:11 WARN]:        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
[02:15:11 WARN]:        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
[02:15:11 WARN]: java.lang.InterruptedException
[02:15:11 WARN]:        at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:386)
[02:15:11 WARN]:        at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073)
[02:15:11 WARN]:        at MobFarmManager3.0.1.7.jar//com.MobFarmManager.Zrips.Util.CleanerManager.lambda$8(CleanerManager.java:292)
[02:15:11 WARN]:        at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
[02:15:11 WARN]:        at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483)
[02:15:11 WARN]:        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
[02:15:11 WARN]:        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
[02:15:11 WARN]:        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
[02:15:11 WARN]:        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
[02:15:11 WARN]:        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
[02:15:11 WARN]: java.lang.InterruptedException
[02:15:11 WARN]:        at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:386)
[02:15:11 WARN]:        at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073)
[02:15:11 WARN]:        at MobFarmManager3.0.1.7.jar//com.MobFarmManager.Zrips.Util.CleanerManager.lambda$8(CleanerManager.java:292)
[02:15:11 WARN]:        at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
[02:15:11 WARN]:        at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483)
[02:15:11 WARN]:        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
[02:15:11 WARN]:        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
[02:15:11 WARN]:        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
[02:15:11 WARN]:        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
[02:15:11 WARN]:        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
[02:15:11 WARN]: java.lang.InterruptedException
[02:15:11 WARN]:        at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:386)
[02:15:11 WARN]:        at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073)
[02:15:11 WARN]:        at MobFarmManager3.0.1.7.jar//com.MobFarmManager.Zrips.Util.CleanerManager.lambda$8(CleanerManager.java:292)
[02:15:11 WARN]:        at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
[02:15:11 WARN]:        at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483)
[02:15:11 WARN]:        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
[02:15:11 WARN]:        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
[02:15:11 WARN]:        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
[02:15:11 WARN]:        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
[02:15:11 WARN]:        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
[02:15:11 WARN]: java.lang.InterruptedException
[02:15:11 WARN]:        at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:386)
[02:15:11 WARN]:        at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073)
[02:15:11 WARN]:        at MobFarmManager3.0.1.7.jar//com.MobFarmManager.Zrips.Util.CleanerManager.lambda$8(CleanerManager.java:292)
[02:15:11 WARN]:        at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
[02:15:11 WARN]:        at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483)
[02:15:11 WARN]:        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
[02:15:11 WARN]:        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
[02:15:11 WARN]:        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
[02:15:11 WARN]:        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
[02:15:11 WARN]:        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
[02:15:11 WARN]: java.lang.InterruptedException
[02:15:11 WARN]:        at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:386)
[02:15:11 WARN]:        at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073)
[02:15:11 WARN]:        at MobFarmManager3.0.1.7.jar//com.MobFarmManager.Zrips.Util.CleanerManager.lambda$8(CleanerManager.java:292)
[02:15:11 WARN]:        at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
[02:15:11 WARN]:        at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483)
[02:15:11 WARN]:        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
[02:15:11 WARN]:        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
[02:15:11 WARN]:        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
[02:15:11 WARN]:        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
[02:15:11 WARN]:        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
```

**Comment by Zrips** [comment]
New version is out
