### ISSUE TITLE
[CONSOLE SPAM] 1.21 Issue

### ISSUE THREAD

**Issue by Valeoria** [Zrips/MobFarmManager#81]
Constantly having console spammed using the latest versions of all plugins/purpur.

`03/08/2024 [16:15:15 WARN]: java.lang.InterruptedException
[16:15:15 WARN]:    at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:386)
[16:15:15 WARN]:    at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073)
[16:15:15 WARN]:    at MobFarmManager3.0.1.7.jar//com.MobFarmManager.Zrips.Util.CleanerManager.lambda$8(CleanerManager.java:292)
[16:15:15 WARN]:    at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
[16:15:15 WARN]:    at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483)
03/08/2024 [16:15:15 WARN]:     at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
[16:15:15 WARN]:    at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
[16:15:15 WARN]:    at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
[16:15:15 WARN]:    at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
[16:15:15 WARN]:    at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
[16:15:15 WARN]: java.lang.InterruptedException
[16:15:15 WARN]:    at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:386)
03/08/2024 
[16:15:15 WARN]:    at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073)
[16:15:15 WARN]:    at MobFarmManager3.0.1.7.jar//com.MobFarmManager.Zrips.Util.CleanerManager.lambda$8(CleanerManager.java:292)
03/08/2024 [16:15:15 WARN]:     at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
[16:15:15 WARN]:    at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483)
[16:15:15 WARN]:    at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
[16:15:15 WARN]:    at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
[16:15:15 WARN]:    at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
[16:15:15 WARN]:    at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
[16:15:15 WARN]:    at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
[16:15:15 WARN]: java.lang.InterruptedException
[16:15:15 WARN]:    at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:386)
[16:15:15 WARN]:    at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073)
[16:15:15 WARN]:    at MobFarmManager3.0.1.7.jar//com.MobFarmManager.Zrips.Util.CleanerManager.lambda$8(CleanerManager.java:292)
[16:15:15 WARN]:    at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
[16:15:15 WARN]:    at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483)
[16:15:15 WARN]:    at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
[16:15:15 WARN]:    at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
[16:15:15 WARN]:    at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
[16:15:15 WARN]:    at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
[16:15:15 WARN]:    at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
[16:15:15 WARN]: java.lang.InterruptedException
[16:15:15 WARN]:    at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:386)
03/08/2024 [16:15:15 WARN]:     at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073)
[16:15:15 WARN]:    at MobFarmManager3.0.1.7.jar//com.MobFarmManager.Zrips.Util.CleanerManager.lambda$8(CleanerManager.java:292)
03/08/2024 [16:15:15 WARN]:     at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
[16:15:15 WARN]:    at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483)
[16:15:15 WARN]:    at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
[16:15:15 WARN]:
03/08/2024 at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
[16:15:15 WARN]:    at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
[16:15:15 WARN]:    at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
03/08/2024 [16:15:15 WARN]:     at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
[16:15:15 WARN]: java.lang.InterruptedException
[16:15:15 WARN]:    at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:386)
[16:15:15 WARN]:    at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073)
[16:15:15 WARN]:    at MobFarmManager3.0.1.7.jar//com.MobFarmManager.Zrips.Util.CleanerManager.lambda$8(CleanerManager.java:292)
[16:15:15 WARN]:    at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
[16:15:15 WARN]:    at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483)
[16:15:15 WARN]:    at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
[16:15:15 WARN]:    at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
[16:15:15 WARN]:    at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
[16:15:15 WARN]:    at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
[16:15:15 WARN]:    at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
[16:15:15 WARN]: java.lang.InterruptedException
[16:15:15 WARN]:    at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:386)
[16:15:15 WARN]:    at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073)
[16:15:15 WARN]:    at MobFarmManager3.0.1.7.jar//com.MobFarmManager.Zrips.Util.CleanerManager.lambda$8(CleanerManager.java:292)
03/08/2024 
[16:15:15 WARN]:    at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
[16:15:15 WARN]:    at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483)
[16:15:15 WARN]:    at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
[16:15:15 WARN]:    at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
03/08/2024 [16:15:15 WARN]:     at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
[16:15:15 WARN]:    at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
03/08/2024 [16:15:15 WARN]:     at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
[16:15:15 WARN]: java.lang.InterruptedException
03/08/2024 [16:15:15 WARN]:     at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:386)
[16:15:15 WARN]:    at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073)
[16:15:15 WARN]:    at MobFarmManager3.0.1.7.jar//com.MobFarmManager.Zrips.Util.CleanerManager.lambda$8(CleanerManager.java:292)
[16:15:15 WARN]:    at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
[16:15:15 WARN]:    at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483)
03/08/2024 
[16:15:15 WARN]:    at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
[16:15:15 WARN]:    at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
[16:15:15 WARN]:    at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
03/08/2024 [16:15:15 WARN]:     at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
[16:15:15 WARN]:    at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
[16:15:15 WARN]: java.lang.InterruptedException
[16:15:15 WARN]:    at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:386)
[16:15:15 WARN]:    at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073)
[16:15:15 WARN]:    at MobFarmManager3.0.1.7.jar//com.MobFarmManager.Zrips.Util.CleanerManager.lambda$8(CleanerManager.java:292)
[16:15:15 WARN]:    at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
[16:15:15 WARN]:    at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483)
[16:15:15 WARN]:    at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
[16:15:15 WARN]:    at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
[16:15:15 WARN]:    at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
[16:15:15 WARN]:    at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
03/08/2024 [16:15:15 WARN]:     at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
[16:15:15 WARN]: java.lang.InterruptedException
[16:15:15 WARN]:    at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:386)
[16:15:15 WARN]:    at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073)
[16:15:15 WARN]:    at MobFarmManager3.0.1.7.jar//com.MobFarmManager.Zrips.Util.CleanerManager.lambda$8(CleanerManager.java:292)
03/08/2024 [16:15:15 WARN]:     at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
[16:15:15 WARN]:    at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483)
[16:15:15 WARN]:    at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
[16:15:15 WARN]:    at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
03/08/2024 [16:15:15 WARN]:     at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
[16:15:15 WARN]:    at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
[16:15:15 WARN]:    at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
[16:15:15 WARN]: java.lang.InterruptedException
[16:15:15 WARN]:    at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:386)
[16:15:15 WARN]:    at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073)
[16:15:15 WARN]:    at MobFarmManager3.0.1.7.jar//com.MobFarmManager.Zrips.Util.CleanerManager.lambda$8(CleanerManager.java:292)
[16:15:15 WARN]:    at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
[16:15:15 WARN]:    at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483)
[16:15:15 WARN]:    at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
[16:15:15 WARN]:    at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
03/08/2024 [16:15:15 WARN]:     at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
[16:15:15 WARN]:    at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
[16:15:15 WARN]:    at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
[16:15:15 WARN]: java.lang.InterruptedException
[16:15:15 WARN]:    at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:386)
[16:15:15 WARN]:    at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073)
[16:15:15 WARN]:    at MobFarmManager3.0.1.7.jar//com.MobFarmManager.Zrips.Util.CleanerManager.lambda$8(CleanerManager.java:292)
03/08/2024 [16:15:15 WARN]:     at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
[16:15:15 WARN]:    at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483)
[16:15:15 WARN]:    at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
[16:15:15 WARN]:    at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
[16:15:15 WARN]:    at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
03/08/2024 [16:15:15 WARN]:     at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
[16:15:15 WARN]:    at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
03/08/2024 [16:15:15 WARN]: java.lang.InterruptedException
[16:15:15 WARN]:    at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:386)
[16:15:15 WARN]:    at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073)
[16:15:15 WARN]:    at MobFarmManager3.0.1.7.jar//com.MobFarmManager.Zrips.Util.CleanerManager.lambda$8(CleanerManager.java:292)
[16:15:15 WARN]:    at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
[16:15:15 WARN]:    at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483)
[16:15:15 WARN]:    at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
03/08/2024 [16:15:15 WARN]:     at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
[16:15:15 WARN]:    at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
[16:15:15 WARN]:    at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
[16:15:15 WARN]:    at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
[16:15:15 WARN]: java.lang.InterruptedException
[16:15:15 WARN]:    at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:386)
[16:15:15 WARN]:    at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073)
[16:15:15 WARN]:    at MobFarmManager3.0.1.7.jar//com.MobFarmManager.Zrips.Util.CleanerManager.lambda$8(CleanerManager.java:292)
[16:15:15 WARN]:    at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
[16:15:15 WARN]:    at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483)
[16:15:15 WARN]:    at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
[16:15:15 WARN]:    at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
[16:15:15 WARN]:    at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
[16:15:15 WARN]:    at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
03/08/2024 [16:15:15 WARN]:     at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
03/08/2024 [16:15:15 WARN]: java.lang.InterruptedException
[16:15:15 WARN]:    at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:386)
[16:15:15 WARN]:    at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073)
03/08/2024 [16:15:15 WARN]:     at MobFarmManager3.0.1.7.jar//com.MobFarmManager.Zrips.Util.CleanerManager.lambda$8(CleanerManager.java:292)
[16:15:15 WARN]:    at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
[16:15:15 WARN]:    at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483)
[16:15:15 WARN]:    at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
[16:15:15 WARN]:    at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
[16:15:15 WARN]:    at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
[16:15:15 WARN]:    at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
03/08/2024 [16:15:15 WARN]:     at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
[16:15:15 WARN]: java.lang.InterruptedException
[16:15:15 WARN]:    at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:386)
[16:15:15 WARN]:    at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073)
[16:15:15 WARN]:    at MobFarmManager3.0.1.7.jar//com.MobFarmManager.Zrips.Util.CleanerManager.lambda$8(CleanerManager.java:292)
[16:15:15 WARN]:    at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
[16:15:15 WARN]:    at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483)
[16:15:15 WARN]:    at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
03/08/2024 [16:15:15 WARN]:     at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
[16:15:15 WARN]:    at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
03/08/2024 [16:15:15 WARN]:     at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
[16:15:15 WARN]:    at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
[16:15:15 WARN]: java.lang.InterruptedException
[16:15:15 WARN]:    at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:386)
[16:15:15 WARN]:    at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073)
[16:15:15 WARN]:    at MobFarmManager3.0.1.7.jar//com.MobFarmManager.Zrips.Util.CleanerManager.lambda$8(CleanerManager.java:292)
03/08/2024 
[16:15:15 WARN]:    at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
[16:15:15 WARN]:    at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483)
[16:15:15 WARN]:    at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
03/08/2024 [16:15:15 WARN]:     at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
[16:15:15 WARN]:    at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
[16:15:15 WARN]:    at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
[16:15:15 WARN]:    at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
[16:15:15 WARN]: java.lang.InterruptedException
03/08/2024 [16:15:15 WARN]:     at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:386)
[16:15:15 WARN]:    at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073)
[16:15:15 WARN]:    at MobFarmManager3.0.1.7.jar//com.MobFarmManager.Zrips.Util.CleanerManager.lambda$8(CleanerManager.java:292)
03/08/2024 [16:15:15 WARN]:     at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
[16:15:15 WARN]:    at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483)
[16:15:15 WARN]:    at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
[16:15:15 WARN]:    at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
[16:15:15 WARN]:    at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
[16:15:15 WARN]:    at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
[16:15:15 WARN]:    at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
[16:15:15 WARN]: java.lang.InterruptedException
[16:15:15 WARN]:    at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:386)
[16:15:15 WARN]:    at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073)
03/08/2024 [16:15:15 WARN]:     at MobFarmManager3.0.1.7.jar//com.MobFarmManager.Zrips.Util.CleanerManager.lambda$8(CleanerManager.java:292)
[16:15:15 WARN]:    at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
[16:15:15 WARN]:    at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483)
[16:15:15 WARN]:    at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
03/08/2024 
[16:15:15 WARN]:    at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
[16:15:15 WARN]:    at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
[16:15:15 WARN]:    at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
[16:15:15 WARN]:    at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)`

**Comment by lDoomerl** [comment]
I have the same issue. Please keep an eye. 

` Current Purpur Version: `1.21-2261-14136b8 (MC: 1.21)
 
` MobFarmManager version 3.0.2.0` - Config: https://pastebin.com/q8ewR95T
 
` CMILib version 1.5.1.1    `
 
 
` Log `- https://pastebin.com/bfi5KWCT

**Comment by Zrips** [comment]
New version is out
