### ISSUE TITLE
java.lang.InterruptedException

### ISSUE THREAD

**Issue by smscentras** [Zrips/MobFarmManager#82]
```
`[17:01:41 WARN]: java.lang.InterruptedException
[17:01:41 WARN]:        at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:386)
[17:01:41 WARN]:        at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073)
[17:01:41 WARN]:        at MobFarmManager3.0.1.7.jar//com.MobFarmManager.Zrips.Util.CleanerManager.lambda$8(CleanerManager.java:292)
[17:01:41 WARN]:        at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
[17:01:41 WARN]:        at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483)
[17:01:41 WARN]:        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
[17:01:41 WARN]:        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
[17:01:41 WARN]:        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
[17:01:41 WARN]:        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
[17:01:41 WARN]:        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
[17:01:41 WARN]: java.lang.InterruptedException
[17:01:41 WARN]:        at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:386)
[17:01:41 WARN]:        at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073)
[17:01:41 WARN]:        at MobFarmManager3.0.1.7.jar//com.MobFarmManager.Zrips.Util.CleanerManager.lambda$8(CleanerManager.java:292)
[17:01:41 WARN]:        at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
[17:01:41 WARN]:        at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483)
[17:01:41 WARN]:        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
[17:01:41 WARN]:        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
[17:01:41 WARN]:        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
[17:01:41 WARN]:        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
[17:01:41 WARN]:        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
[17:01:41 WARN]: java.lang.InterruptedException
[17:01:41 WARN]:        at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:386)
[17:01:41 WARN]:        at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073)
[17:01:41 WARN]:        at MobFarmManager3.0.1.7.jar//com.MobFarmManager.Zrips.Util.CleanerManager.lambda$8(CleanerManager.java:292)
[17:01:41 WARN]:        at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
[17:01:41 WARN]:        at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483)
[17:01:41 WARN]:        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
[17:01:41 WARN]:        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
[17:01:41 WARN]:        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
[17:01:41 WARN]:        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
[17:01:41 WARN]:        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
[17:01:41 WARN]: java.lang.InterruptedException
[17:01:41 WARN]:        at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:386)
[17:01:41 WARN]:        at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073)
[17:01:41 WARN]:        at MobFarmManager3.0.1.7.jar//com.MobFarmManager.Zrips.Util.CleanerManager.lambda$8(CleanerManager.java:292)
[17:01:41 WARN]:        at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
[17:01:41 WARN]:        at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483)
[17:01:41 WARN]:        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
[17:01:41 WARN]:        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
[17:01:41 WARN]:        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
[17:01:41 WARN]:        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
[17:01:41 WARN]:        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
[17:01:41 WARN]: java.lang.InterruptedException
[17:01:41 WARN]:        at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:386)
[17:01:41 WARN]:        at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073)
[17:01:41 WARN]:        at MobFarmManager3.0.1.7.jar//com.MobFarmManager.Zrips.Util.CleanerManager.lambda$8(CleanerManager.java:292)
[17:01:41 WARN]:        at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
[17:01:41 WARN]:        at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483)
[17:01:41 WARN]:        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
[17:01:41 WARN]:        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
[17:01:41 WARN]:        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
[17:01:41 WARN]:        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
[17:01:41 WARN]:        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJ
```oinWorkerThread.java:188)`

**Comment by smscentras** [comment]
same problem sometimes...
Big flood in console.
PurPur 1.20.4

**Comment by Zrips** [comment]
New version is out
