### ISSUE TITLE
New MobFarmmanger 3.0.1.9 spammed itself and citisenz

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/MobFarmManager#85]
```
[18:51:59] [Server thread/WARN]: java.lang.InterruptedException
[18:51:59] [Server thread/WARN]: 	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:386)
[18:51:59] [Server thread/WARN]: 	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073)
[18:51:59] [Server thread/WARN]: 	at MobFarmManager_3.0.1.9.jar//com.MobFarmManager.Zrips.Util.CleanerManager.lambda$8(CleanerManager.java:299)
[18:51:59] [Server thread/WARN]: 	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
[18:51:59] [Server thread/WARN]: 	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
[18:51:59] [Server thread/WARN]: 	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2179)
[18:51:59] [Server thread/WARN]: 	at org.bukkit.craftbukkit.CraftWorld.lambda$getChunkAtAsync$14(CraftWorld.java:2432)
[18:51:59] [Server thread/WARN]: 	at net.minecraft.server.TickTask.run(TickTask.java:18)
[18:51:59] [Server thread/WARN]: 	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151)
[18:51:59] [Server thread/WARN]: 	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24)
[18:51:59] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1537)
[18:51:59] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201)
[18:51:59] [Server thread/WARN]: 	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125)
[18:51:59] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1514)
[18:51:59] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1507)
[18:51:59] [Server thread/WARN]: 	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135)
[18:51:59] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1466)
[18:51:59] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1588)
[18:51:59] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1304)
[18:51:59] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330)
[18:51:59] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:1583)
[18:51:59] [Server thread/WARN]: java.lang.InterruptedException
[18:51:59] [Server thread/WARN]: 	at java.base/java.util.concurrent.ForkJoinTask.reportExecutionException(ForkJoinTask.java:577)
[18:51:59] [Server thread/WARN]: 	at java.base/java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:993)
[18:51:59] [Server thread/WARN]: 	at Citizens_2.0.35_Build3512.jar//net.citizensnpcs.api.LocationLookup.run(LocationLookup.java:166)
[18:51:59] [Server thread/WARN]: 	at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:86)
[18:51:59] [Server thread/WARN]: 	at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:475)
[18:51:59] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1726)
[18:51:59] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:473)
[18:51:59] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1598)
[18:51:59] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1304)
[18:51:59] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330)
[18:51:59] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:1583)
```
after downgrade to 3.0.1.8 both errors disapeast

To Reproduce might use some citizens and version 3.0.1.9 of momfarmmanager on a 1.21.1 paper server

**Comment by DarkyG2** [comment]
I have the same issue on Folia, here is my error: 
```
[20:54:34 WARN]: java.lang.InterruptedException
[20:54:34 WARN]:        at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:386)
[20:54:34 WARN]:        at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073)
[20:54:34 WARN]:        at MobFarmManager3.0.1.9.jar//com.MobFarmManager.Zrips.Util.CleanerManager.lambda$8(CleanerManager.java:299)
[20:54:34 WARN]:        at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
[20:54:34 WARN]:        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
[20:54:34 WARN]:        at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2179)
[20:54:34 WARN]:        at org.bukkit.craftbukkit.v1_20_R3.CraftWorld.lambda$getChunkAtAsync$17(CraftWorld.java:2553)
[20:54:34 WARN]:        at io.papermc.paper.threadedregions.RegionizedTaskQueue$PrioritisedQueue$ChunkBasedPriorityTask.executeInternal(RegionizedTaskQueue.java:504)
[20:54:34 WARN]:        at io.papermc.paper.threadedregions.RegionizedTaskQueue$PrioritisedQueue.executeTask(RegionizedTaskQueue.java:434)
[20:54:34 WARN]:        at io.papermc.paper.threadedregions.RegionizedTaskQueue$RegionTaskQueueData.drainTasks(RegionizedTaskQueue.java:263)
[20:54:34 WARN]:        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1634)
[20:54:34 WARN]:        at io.papermc.paper.threadedregions.TickRegions$ConcreteRegionTickHandle.tickRegion(TickRegions.java:408)
[20:54:34 WARN]:        at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:404)
[20:54:34 WARN]:        at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:525)
[20:54:34 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
[20:54:34 WARN]: java.lang.InterruptedException
[20:54:34 WARN]:        at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:386)
[20:54:34 WARN]:        at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073)
[20:54:34 WARN]:        at MobFarmManager3.0.1.9.jar//com.MobFarmManager.Zrips.Util.CleanerManager.lambda$8(CleanerManager.java:299)
[20:54:34 WARN]:        at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
[20:54:34 WARN]:        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
[20:54:34 WARN]:        at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2179)
[20:54:34 WARN]:        at org.bukkit.craftbukkit.v1_20_R3.CraftWorld.lambda$getChunkAtAsync$17(CraftWorld.java:2553)
[20:54:34 WARN]:        at io.papermc.paper.threadedregions.RegionizedTaskQueue$PrioritisedQueue$ChunkBasedPriorityTask.executeInternal(RegionizedTaskQueue.java:504)
[20:54:34 WARN]:        at io.papermc.paper.threadedregions.RegionizedTaskQueue$PrioritisedQueue.executeTask(RegionizedTaskQueue.java:434)
[20:54:34 WARN]:        at io.papermc.paper.threadedregions.RegionizedTaskQueue$RegionTaskQueueData.drainTasks(RegionizedTaskQueue.java:263)
[20:54:34 WARN]:        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1634)
[20:54:34 WARN]:        at io.papermc.paper.threadedregions.TickRegions$ConcreteRegionTickHandle.tickRegion(TickRegions.java:408)
[20:54:34 WARN]:        at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:404)
[20:54:34 WARN]:        at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:525)
[20:54:34 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
[20:54:34 WARN]: java.lang.InterruptedException
[20:54:34 WARN]:        at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:386)
[20:54:34 WARN]:        at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073)
[20:54:34 WARN]:        at MobFarmManager3.0.1.9.jar//com.MobFarmManager.Zrips.Util.CleanerManager.lambda$8(CleanerManager.java:299)
[20:54:34 WARN]:        at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
[20:54:34 WARN]:        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
[20:54:34 WARN]:        at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2179)
[20:54:34 WARN]:        at org.bukkit.craftbukkit.v1_20_R3.CraftWorld.lambda$getChunkAtAsync$17(CraftWorld.java:2553)
[20:54:34 WARN]:        at io.papermc.paper.threadedregions.RegionizedTaskQueue$PrioritisedQueue$ChunkBasedPriorityTask.executeInternal(RegionizedTaskQueue.java:504)
[20:54:34 WARN]:        at io.papermc.paper.threadedregions.RegionizedTaskQueue$PrioritisedQueue.executeTask(RegionizedTaskQueue.java:434)
[20:54:34 WARN]:        at io.papermc.paper.threadedregions.RegionizedTaskQueue$RegionTaskQueueData.drainTasks(RegionizedTaskQueue.java:263)
[20:54:34 WARN]:        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1634)
[20:54:34 WARN]:        at io.papermc.paper.threadedregions.TickRegions$ConcreteRegionTickHandle.tickRegion(TickRegions.java:408)
[20:54:34 WARN]:        at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:404)
[20:54:34 WARN]:        at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:525)
[20:54:34 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
```

**Comment by smscentras** [comment]
I have the same issue on Purpur 1.21.0
P.S. don't use Citizens :)

**Comment by CloudeLecaw** [comment]
We Downgrated to 3.0.1.8

After the Downgrade the error from MobFarmManager stopped (also the error i posted unter it with Citizens (they came gegether each time...)

So i asume this error als was created by the new MobFarmManager

**Comment by CloudeLecaw** [comment]
> I have the same issue on Purpur 1.21.0 P.S. don't use Citizens :)

what? why not? It one of the most pooular and most used npc plugins arround
Also tons of plugins  we have use Citizens hooks :-)

**Comment by smscentras** [comment]
> > I have the same issue on Purpur 1.21.0 P.S. don't use Citizens :)
> 
> what? why not? It one of the most pooular and most used npc plugins arround Also tons of plugins we have use Citizens hooks :-)

Oh, i mean i have not using Citizens :)
This plugin use a lot of memory and so on... All know that.

**Comment by Z3r0xh** [comment]
I want to comment that after receiving this error I have had problems when saving the players' stats, thus breaking the saving of hours and statistics. This has caused the files of the players who were playing during that moment to be corrupted during the next restart.
`[18:06:34] [Server thread/ERROR]: Couldn't save stats
java.nio.channels.ClosedByInterruptException: null
	at java.base/java.nio.channels.spi.AbstractInterruptibleChannel.end(AbstractInterruptibleChannel.java:200) ~[?:?]
	at java.base/java.nio.channels.Channels$WritableByteChannelImpl.write(Channels.java:394) ~[?:?]
	at org.apache.commons.io.IOUtils.write(IOUtils.java:3644) ~[commons-io-2.15.1.jar:2.15.1]
	at org.apache.commons.io.FileUtils.writeStringToFile(FileUtils.java:3517) ~[commons-io-2.15.1.jar:2.15.1]
	at org.apache.commons.io.FileUtils.writeStringToFile(FileUtils.java:3467) ~[commons-io-2.15.1.jar:2.15.1]
	at net.minecraft.stats.ServerStatsCounter.save(ServerStatsCounter.java:78) ~[universe-1.21.jar:1.21-DEV-a62044c]
	at net.minecraft.server.players.PlayerList.save(PlayerList.java:602) ~[universe-1.21.jar:1.21-DEV-a62044c]
	at net.minecraft.server.players.PlayerList.remove(PlayerList.java:655) ~[universe-1.21.jar:1.21-DEV-a62044c]
	at net.minecraft.server.players.PlayerList.remove(PlayerList.java:615) ~[universe-1.21.jar:1.21-DEV-a62044c]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.removePlayerFromWorld(ServerGamePacketListenerImpl.java:2055) ~[universe-1.21.jar:1.21-DEV-a62044c]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.onDisconnect(ServerGamePacketListenerImpl.java:2035) ~[universe-1.21.jar:1.21-DEV-a62044c]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.onDisconnect(ServerGamePacketListenerImpl.java:2022) ~[universe-1.21.jar:1.21-DEV-a62044c]
	at net.minecraft.network.Connection.handleDisconnection(Connection.java:928) ~[universe-1.21.jar:1.21-DEV-a62044c]
	at net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:262) ~[universe-1.21.jar:1.21-DEV-a62044c]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1837) ~[universe-1.21.jar:1.21-DEV-a62044c]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:499) ~[universe-1.21.jar:1.21-DEV-a62044c]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1612) ~[universe-1.21.jar:1.21-DEV-a62044c]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1312) ~[universe-1.21.jar:1.21-DEV-a62044c]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:335) ~[universe-1.21.jar:1.21-DEV-a62044c]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]`

**Comment by Chevels** [comment]
Same here, infinite console spamming when a player is connected, with lastest cmilib (1.5.1.1). I had to downgrade to previous version (_Mob Farm Manager version 3.0.1.8_) and it's ok.

**Comment by bobhenl** [comment]
I can confirm here

**Comment by Zrips** [comment]
New version is out
