### ISSUE TITLE
concurrent error

### ISSUE THREAD

**Issue by bobhenl** [Zrips/MobFarmManager#87]
Hello, I'm getting this error:
```yml
java.lang.InterruptedException
        at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:386)
        at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073)
        at MobFarmManager3.0.2.1.jar//com.MobFarmManager.Zrips.Util.CleanerManager.lambda$8(CleanerManager.java:315)
        at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
        at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base/java.lang.Thread.run(Thread.java:1583)
```

```
14:37:15 INFO]: Current Purpur Version: 1.21.1-2298-a61db94 (MC: 1.21.1)*
* You are 1 version(s) behind
Download the new version at: https://purpurmc.org/downloads
Previous: 1.21.1-2297-ef12ede (MC: 1.21.1)
```

**Comment by Zrips** [comment]
Should have been resolved with .2 update
