### ISSUE TITLE
NoSuchMethodError

### ISSUE THREAD

**Issue by deHasher** [Zrips/MobFarmManager#89]
Core: Purpur version git-Purpur-1171 (MC: 1.16.5)
CMI: 9.7.5.9 SqLite
CMILib: 1.5.1.3

```
[02:30:04] [Server thread/INFO]: Flugegeheimen issued server command: /rtp
[02:30:10] [Server thread/ERROR]: Could not pass event CreatureSpawnEvent to MobFarmManager v3.0.2.1
java.lang.NoSuchMethodError: 'org.bukkit.Chunk org.bukkit.World.getChunkAt(int, int, boolean)'
	at com.MobFarmManager.Zrips.Util.CleanerManager.getChunkAt(CleanerManager.java:712) ~[?:?]
	at com.MobFarmManager.Zrips.Util.CleanerManager.getEntitiesFromChunksSync(CleanerManager.java:685) ~[?:?]
	at com.MobFarmManager.Zrips.Util.CleanerManager.checkEntitiesSync(CleanerManager.java:244) ~[?:?]
	at com.MobFarmManager.Zrips.Util.CleanerManager.cleanOnEntitySpawn(CleanerManager.java:233) ~[?:?]
	at com.MobFarmManager.Zrips.Listeners.EntityListener.onCreatureSpawnEventAsync(EntityListener.java:59) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor154.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Purpur-1171]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.16.5.jar:git-Purpur-1171]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Purpur-1171]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.16.5.jar:git-Purpur-1171]
	at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callCreatureSpawnEvent(CraftEventFactory.java:734) ~[patched_1.16.5.jar:git-Purpur-1171]
	at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.doEntityAddEventCalling(CraftEventFactory.java:652) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.WorldServer.addEntity0(WorldServer.java:1906) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.WorldServer.addEntity(WorldServer.java:1807) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.WorldAccess.lambda$addAllEntities$0(WorldAccess.java:16) ~[patched_1.16.5.jar:git-Purpur-1171]
	at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411) ~[?:?]
	at java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:734) ~[?:?]
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762) ~[?:?]
	at net.minecraft.server.v1_16_R3.WorldAccess.addAllEntities(WorldAccess.java:16) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.SpawnerCreature.spawnMobsInternal(SpawnerCreature.java:295) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.SpawnerCreature.spawnMobs(SpawnerCreature.java:221) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.SpawnerCreature.a(SpawnerCreature.java:197) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.ChunkProviderServer.tickChunks(ChunkProviderServer.java:1057) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.ChunkProviderServer.tick(ChunkProviderServer.java:950) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.WorldServer.doTick(WorldServer.java:1060) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1567) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:449) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1416) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1142) ~[patched_1.16.5.jar:git-Purpur-1171]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:293) ~[patched_1.16.5.jar:git-Purpur-1171]
	at java.lang.Thread.run(Thread.java:1583) [?:?]
```

**Comment by Zrips** [comment]
Should be resolved with next update

**Comment by deHasher** [comment]
Same error, but on version 1.17.1, MFM version: 3.0.2.3
```
'org.bukkit.Chunk org.bukkit.World.getChunkAt(int, int, boolean)'
 at MobFarmManager.jar//com.MobFarmManager.Zrips.Util.CleanerManager.getChunkAt(CleanerManager.java:755)
 at MobFarmManager.jar//com.MobFarmManager.Zrips.Util.CleanerManager.getEntitiesFromChunksSync(CleanerManager.java:743)
 at MobFarmManager.jar//com.MobFarmManager.Zrips.Util.CleanerManager.checkEntitiesSync(CleanerManager.java:234)
 at MobFarmManager.jar//com.MobFarmManager.Zrips.Util.CleanerManager.cleanOnEntitySpawn(CleanerManager.java:223)
 at MobFarmManager.jar//com.MobFarmManager.Zrips.Listeners.EntityListener.onCreatureSpawnEventAsync(EntityListener.java:59)
 at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor123.execute(Unknown Source)
 at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
 at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76)
 at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
 at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628)
 at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.callCreatureSpawnEvent(CraftEventFactory.java:738)
 at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.doEntityAddEventCalling(CraftEventFactory.java:643)
 at net.minecraft.server.level.WorldServer.addEntity0(WorldServer.java:1483)
 at net.minecraft.server.level.WorldServer.addEntity(WorldServer.java:1395)
 at net.minecraft.world.level.WorldAccess.lambda$addAllEntities$0(WorldAccess.java:16)
 at java.base/java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411)
 at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
 at net.minecraft.world.level.WorldAccess.addAllEntities(WorldAccess.java:16)
 at net.minecraft.world.level.SpawnerCreature.spawnCategoryForPosition(SpawnerCreature.java:310)
 at net.minecraft.world.level.SpawnerCreature.spawnCategoryForChunk(SpawnerCreature.java:227)
 at net.minecraft.world.level.SpawnerCreature.a(SpawnerCreature.java:185)
 at net.minecraft.server.level.ChunkProviderServer.tickChunks(ChunkProviderServer.java:1046)
 at net.minecraft.server.level.ChunkProviderServer.tick(ChunkProviderServer.java:935)
 at net.minecraft.server.level.WorldServer.doTick(WorldServer.java:756)
 at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1652)
 at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:528)
 at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1507)
 at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1300)
 at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:322)
 at java.base/java.lang.Thread.run(Thread.java:1583)
```
