### ISSUE TITLE
70% LOAD OF TICKS! (Latest)

### ISSUE THREAD

**Issue by GG-MD** [Zrips/MobFarmManager#90]
Versions server: 1.21.1 PurPur latest build. 

Console error: 
```

[13:01:50] [pool-91-thread-1/WARN]: java.lang.InterruptedException
[13:01:50] [pool-91-thread-1/WARN]: 	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:386)
[13:01:50] [pool-91-thread-1/WARN]: 	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073)
[13:01:50] [pool-91-thread-1/WARN]: 	at MobFarmManager3.0.2.1.jar//com.MobFarmManager.Zrips.Util.CleanerManager.lambda$8(CleanerManager.java:315)
[13:01:50] [pool-91-thread-1/WARN]: 	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
[13:01:50] [pool-91-thread-1/WARN]: 	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
[13:01:50] [pool-91-thread-1/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[13:01:50] [pool-91-thread-1/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[13:01:50] [pool-91-thread-1/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:1583)
[13:01:50] [pool-91-thread-1/WARN]: java.lang.InterruptedException
[13:01:50] [pool-91-thread-1/WARN]: 	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:386)
[13:01:50] [pool-91-thread-1/WARN]: 	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073)
[13:01:50] [pool-91-thread-1/WARN]: 	at MobFarmManager3.0.2.1.jar//com.MobFarmManager.Zrips.Util.CleanerManager.lambda$8(CleanerManager.java:315)
[13:01:50] [pool-91-thread-1/WARN]: 	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
[13:01:50] [pool-91-thread-1/WARN]: 	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
[13:01:50] [pool-91-thread-1/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[13:01:50] [pool-91-thread-1/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[13:01:50] [pool-91-thread-1/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:1583)
[13:01:50] [pool-91-thread-5/WARN]: java.lang.InterruptedException
[13:01:50] [pool-91-thread-5/WARN]: 	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:386)
[13:01:50] [pool-91-thread-5/WARN]: 	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073)
[13:01:50] [pool-91-thread-5/WARN]: 	at MobFarmManager3.0.2.1.jar//com.MobFarmManager.Zrips.Util.CleanerManager.lambda$8(CleanerManager.java:315)
[13:01:50] [pool-91-thread-5/WARN]: 	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
[13:01:50] [pool-91-thread-5/WARN]: 	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
[13:01:50] [pool-91-thread-5/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[13:01:50] [pool-91-thread-5/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[13:01:50] [pool-91-thread-5/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:1583)
[13:01:50] [pool-91-thread-5/WARN]: java.lang.InterruptedException
[13:01:50] [pool-91-thread-5/WARN]: 	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:386)
[13:01:50] [pool-91-thread-5/WARN]: 	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073)
[13:01:50] [pool-91-thread-5/WARN]: 	at MobFarmManager3.0.2.1.jar//com.MobFarmManager.Zrips.Util.CleanerManager.lambda$8(CleanerManager.java:315)
[13:01:50] [pool-91-thread-5/WARN]: 	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
[13:01:50] [pool-91-thread-5/WARN]: 	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
[13:01:50] [pool-91-thread-5/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[13:01:50] [pool-91-thread-5/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[13:01:50] [pool-91-thread-5/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:1583)
[13:01:50] [pool-91-thread-5/WARN]: java.lang.InterruptedException
[13:01:50] [pool-91-thread-5/WARN]: 	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:386)
[13:01:50] [pool-91-thread-5/WARN]: 	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073)
[13:01:50] [pool-91-thread-5/WARN]: 	at MobFarmManager3.0.2.1.jar//com.MobFarmManager.Zrips.Util.CleanerManager.lambda$8(CleanerManager.java:315)
[13:01:50] [pool-91-thread-5/WARN]: 	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
[13:01:50] [pool-91-thread-5/WARN]: 	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
[13:01:50] [pool-91-thread-5/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[13:01:50] [pool-91-thread-5/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[13:01:50] [pool-91-thread-5/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:1583)
[13:01:50] [pool-91-thread-5/WARN]: java.lang.InterruptedException
[13:01:50] [pool-91-thread-5/WARN]: 	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:386)
[13:01:50] [pool-91-thread-5/WARN]: 	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073)
[13:01:50] [pool-91-thread-5/WARN]: 	at MobFarmManager3.0.2.1.jar//com.MobFarmManager.Zrips.Util.CleanerManager.lambda$8(CleanerManager.java:315)
[13:01:50] [pool-91-thread-5/WARN]: 	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
[13:01:50] [pool-91-thread-5/WARN]: 	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
[13:01:50] [pool-91-thread-5/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[13:01:50] [pool-91-thread-5/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[13:01:50] [pool-91-thread-5/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:1583)
[13:01:50] [Paper Async Task Handler Thread - 1/INFO]: [⚡] Tick #65340 lasted 275.8 ms. (451.6% increase from avg)

```

Fixed this pls!!

**Comment by GG-MD** [comment]
@Zrips

**Comment by GG-MD** [comment]
@Zrips 
....

**Comment by Zrips** [comment]
Should be addressed tomorrow

**Comment by Zrips** [comment]
New version is out
